techbow-homework/homework

src/main/java/com/techbow/homework/y2021/m03/Taiyi/LC124.java, src/main/java/com/techbow/homework/y2021/m03/Taiyi/LC230.java, src/main/java/com/techbow/homework/y2021/m03/Taiyi/LC252.java, src/main/java/com/techbow/homework/y2021/m03/Taiyi/LC253.java, src/main/java/com/techbow/homework/y2021/m03/Taiyi/LC295.java
=> Tye 9/26/2021

pom.xml, src/main/java/com/techbow/homework/y2021/m09/QiyueWang/LC1197MinKnightMoves.java, src/main/java/com/techbow/homework/y2021/m09/QiyueWang/LC121BestTimeToBuyAndSellStock.java, src/main/java/com/techbow/homework/y2021/m09/QiyueWang/LC1381DesignAStackWithIncrementOperation.java, src/main/java/com/techbow/homework/y2021/m09/QiyueWang/LC146LRUCache.java, src/main/java/com/techbow/homework/y2021/m09/QiyueWang/LC1481LeastNumberOfUniqueIntegersAfterKRemovals.java, src/main/java/com/techbow/homework/y2021/m09/QiyueWang/LC1743RestoreTheArrayFromAdjacentPairs.java, src/main/java/com/techbow/homework/y2021/m09/QiyueWang/LC2029StoneGameIX.java, src/main/java/com/techbow/homework/y2021/m09/QiyueWang/LC264UglyNumberII.java, src/main/java/com/techbow/homework/y2021/m09/QiyueWang/LC407TrappingRainWaterII.java, src/main/java/com/techbow/homework/y2021/m09/QiyueWang/LC41FirstMissingPositive.java, src/main/java/com/techbow/homework/y2021/m09/QiyueWang/LC423ReconstructOriginalDigitsFromEnglish.java, src/main/java/com/techbow/homework/y2021/m09/QiyueWang/LC42TrappingRainWater.java, src/main/java/com/techbow/homework/y2021/m09/QiyueWang/LC492ConstructTheRectangle.java, src/main/java/com/techbow/homework/y2021/m09/QiyueWang/LC55JumpGame.java, src/main/java/com/techbow/homework/y2021/m09/QiyueWang/LC647PalindromicSubstrings.java, src/main/java/com/techbow/homework/y2021/m09/QiyueWang/LC698PartitionToKEqualSumSubsets.java, src/main/java/com/techbow/homework/y2021/m09/QiyueWang/LC725SplitLinkedListInPairs.java, src/main/java/com/techbow/homework/y2021/m09/QiyueWang/LC84LargestRectangleInHistogram.java, src/main/java/com/techbow/homework/y2021/m09/QiyueWang/LC922SortArrayByParityII.java, src/main/java/com/techbow/homework/y2021/m09/QiyueWang/LC929UniqueEmailAddresses.java, src/main/java/com/techbow/homework/y2021/m09/QiyueWang/MetroLandFestival.java, src/main/java/com/techbow/homework/y2021/m09/QiyueWang/ScatterPalindrome.java
=> 王七月 09/26/2021 - 09/29/2021

src/main/java/com/techbow/homework/y2021/m10/mingyu/mingyuhw.java
=> Jacky_210803_092921

src/main/java/com/techbow/homework/y2021/m09/boyuan/LC_02.java, src/main/java/com/techbow/homework/y2021/m09/boyuan/小宋小宋/BFS_102.java, src/main/java/com/techbow/homework/y2021/m09/boyuan/小宋小宋/BFS_78.java, src/main/java/com/techbow/homework/y2021/m09/boyuan/小宋小宋/LC_02.java, src/main/java/com/techbow/homework/y2021/m09/boyuan/小宋小宋/TreeNodeImpl.java
=> 小宋小宋-20210929

src/main/java/com/techbow/homework/y2021/m09/LIYANG/LC275BinaryTreePaths.java
=> 10/3/2021- #first - li yang

homwork.iml, src/main/java/com/techbow/homework/y2021/m09/boyuan/YiqingLiu.txt
=> yueboningdi20210301 10/01/2021

src/main/java/com/techbow/homework/y2021/m09/tingtingtang/HelloWorld.java
=> Brenda20210903 first commit

src/main/java/com/techbow/homework/y2021/m10/mengyu/LC25SwapNodesInPairs.java
=> mengyu 20201207 OCT/5/2021 

src/main/java/com/techbow/homework/y2021/m09/dqj/Test.java
=> dqj 10/05/2021

src/main/java/m10/dantewu/LC_01.java
=> LC_01.java

src/main/java/com/techbow/homework/y2021/m10/mingyu/开小号Note
=> 2021-10-06special note 20210803

src/main/java/com/techbow/homework/y2021/m10/LiYang/HW10072021, src/main/java/com/techbow/homework/y2021/m10/LiYang/LC411JustGenerateAbbrev.java
=> HW & LC411

homwork.iml, src/main/java/com/techbow/homework/y2021/m10/diJieShuiBuXing/算法陪练/linkedlist/LC203RemoveLinkedListElements.java, src/main/java/com/techbow/homework/y2021/m10/diJieShuiBuXing/算法陪练/linkedlist/LC237DeleteNodeinaLinkedList.java, src/main/java/com/techbow/homework/y2021/m10/diJieShuiBuXing/算法陪练/linkedlist/LC83RemoveDuplicatesfromSortedList.java
=> 10/09 迪姐睡不醒

src/main/java/com/techbow/homework/y2021/m10/LiYang/LC140wordBreak, src/main/java/com/techbow/homework/y2021/m10/LiYang/LC403ForgJump
=> Li Yang20210512 - LC403&LC140 - 10/9/2021

src/main/java/com/techbow/homework/y2021/m10/Jacob/LC_24.java, src/main/java/com/techbow/homework/y2021/m10/mengyu/ListNode.java
=> 武★尐.🍁20210406 Oct 10

src/main/java/com/techbow/homework/y2021/m10/kuixiaosu/LC_35.java
Homework. Review/approve welcome!
=> 小小酥 20210403 10/11/2021

src/main/java/com/techbow/homework/y2021/m10/LiYang/LC282
=> LiYang20210512-LC282-10/10/2021

src/main/java/com/techbow/homework/y2021/m10/eva/LC_543.java, src/main/java/com/techbow/homework/y2021/m10/eva/TreeNode.java
=> Eva20210112 Oct 8

src/main/java/com/techbow/homework/y2021/m10/kuixiaosu/LC_74.java
=> 小小酥 20210403 10/13/2021

src/main/java/com/techbow/homework/y2021/m10/kuixiaosu/LC_81.java
=> 小小酥 20210403 10/14/2021

src/main/java/com/techbow/homework/y2021/m10/zekun/LC0016_TwoPointer_ThreeSumClosest.java, src/main/java/com/techbow/homework/y2021/m10/zekun/LC0133_Graph_CloneGraph_BFS.java, src/main/java/com/techbow/homework/y2021/m10/zekun/LC0133_Graph_CloneGraph_DFS.java, src/main/java/com/techbow/homework/y2021/m10/zekun/LC0139_TwoPointers_GasStation.java, src/main/java/com/techbow/homework/y2021/m10/zekun/LC0159_SlidingWindow_LongestSubstringTwoDistictCharacter.java, src/main/java/com/techbow/homework/y2021/m10/zekun/LC0259_TwoPointers_ThreeSumSmaller.java, src/main/java/com/techbow/homework/y2021/m10/zekun/LC0269_AlienDictionary.java, src/main/java/com/techbow/homework/y2021/m10/zekun/LC0323_Graph_ConnectedComponent.java, src/main/java/com/techbow/homework/y2021/m10/zekun/LC0424_TwoPointerSlidingWindow_LongestRepeatingChar.java, src/main/java/com/techbow/homework/y2021/m10/zekun/LC0642_DesignSearchAutocompleteSystem.java, src/main/java/com/techbow/homework/y2021/m10/zekun/LC285_Tree_BSTInorderSuccessor.java
with '#' will be ignored, and an empty message aborts the commit.
=> Zekun Lin @20210310 - 20211016;

src/main/java/com/techbow/homework/y2021/m10/LiYang/LC333, src/main/java/com/techbow/homework/y2021/m10/LiYang/LC416
=> Li Yang20210512 - LC416 - 10/14/2021

src/main/java/com/techbow/homework/y2021/m10/LiYang/LC333
=> li yang20210512 - LC333 - 10/18/2021

src/main/java/com/techbow/homework/y2021/m10/LiYang/LC156_binary_tree_upside_down, src/main/java/com/techbow/homework/y2021/m10/LiYang/LC701_insert_into_BST
=> li yang20210512 - LC156,701 - 10/27/2021

src/main/java/com/techbow/homework/y2021/m10/LiYang/LC1143_Longest_common_subsequence, src/main/java/com/techbow/homework/y2021/m10/LiYang/LC146_LRU_cache, src/main/java/com/techbow/homework/y2021/m10/LiYang/LC41_first_missing_positive
=> li yang20210512 - LC1143,146,41 - 10/31/2021

src/main/java/com/techbow/homework/y2021/m10/zekun/LC0545_BinaryTreeBoundaryB.java
=> ZekunLin@20210310 - 20211101

src/main/java/com/techbow/homework/y2021/m10/LiYang/LC207_Course_schedule
=> li yang20210512 - LC207 - 11/2/2021

src/main/java/com/techbow/homework/y2021/m10/LiYang/LC210_course_schedule_II, src/main/java/com/techbow/homework/y2021/m10/LiYang/LC261_Graph_valid_tree
=> li yang20210512 - LC210,261 - 11/3/2021

src/main/java/com/techbow/homework/y2021/m10/zekun/LC0160_LinkedList_IntersectionOfTwoLinkedList.java, src/main/java/com/techbow/homework/y2021/m10/zekun/LC0445_LinkedList_SumTwoNumberII.java
走到尽头见不到你，于是走过你来时的路，等到相遇时才发现，你也走过我来时的路～
=> ZekunLin@20210310-20211106

homwork.iml, src/main/java/com/techbow/homework/y2021/m11/xiaoyanxu/LC0005.java
=> First Pull Request

src/main/java/com/techbow/homework/y2021/m10/zekun/LC0005_LongestPalindrome.java, src/main/java/com/techbow/homework/y2021/m10/zekun/LC0012_IntegerToRoman.java, src/main/java/com/techbow/homework/y2021/m10/zekun/LC0041_FirstMissingInteger.java, src/main/java/com/techbow/homework/y2021/m10/zekun/LC0149_MaximumPointsInSameLine.java, src/main/java/com/techbow/homework/y2021/m10/zekun/LC0229_MajarityElementII.java, src/main/java/com/techbow/homework/y2021/m10/zekun/LC0238_ProductExceptItself.java, src/main/java/com/techbow/homework/y2021/m10/zekun/LC0438_AllAnagram.java, src/main/java/com/techbow/homework/y2021/m10/zekun/LC0463_IslandPerimeter.java
String array/ 龟兔赛跑算法/array做hashmap/  and more
=> Zekun Lin @ 20210310 20211111
